using UnityEngine;

public class PowerModule : PrimaryModule
{
    /// <summary>
    /// Bars of energy generated per second.
    /// </summary>
    public float power = 1;
    
    /// <summary>
    /// Type of energy generated by module.
    /// </summary>
    public Common.SoundType soundType = Common.SoundType.None;
    
    protected override void Start()
    {
        base.Start();

        CombatStats["power"] = power;
        CombatStats["rate"] = 0;
        CombatStats["shields"] = 0;
    }
}
