using System.Collections.Generic;
using UnityEngine;

public class PowerModule : PrimaryModule, IReactorModule
{
    /// <summary>
    /// Bars of energy generated per second.
    /// </summary>
    public float power = 1;
    
    // /// <summary>
    // /// Type of energy generated by module.
    // /// </summary>
    // public Common.SoundType soundType = Common.SoundType.None;

    public override string Description()
    {
        return "Generates energy for the reactor. Chaining power modules will increase overall output.";
    }

    public override string Info()
    {
        return $"Currently generating {power} untyped energy per second.";
    }

    public Dictionary<Common.SoundType, float> ChangeEnergy(Dictionary<Common.SoundType, float> energy)
    {
        energy[Common.SoundType.Pure] += power;
        return energy;
    }

    // public IReactorModule.ReactorStats MyReactorStats()
    // {
    //     return new IReactorModule.ReactorStats()
    //     {
    //         PowerGenerated = power
    //     };
    // }
    public override Dictionary<string, float> ChangeMusicParams(Dictionary<string, float> musicParams)
    {
        throw new System.NotImplementedException();
    }
}
