using System.Collections.Generic;
using UnityEngine;

public class PowerModule : PrimaryModule, IReactorModule
{
    /// <summary>
    /// Bars of energy generated per second.
    /// </summary>
    public float power = 1;
    
    // /// <summary>
    // /// Type of energy generated by module.
    // /// </summary>
    // public Common.SoundType soundType = Common.SoundType.None;

    public override string Description()
    {
        return "Generates energy for the reactor.";
    }

    public override string Info()
    {
        return $"Currently generating {power} untyped energy per second.";
    }

    public override Dictionary<string, float> MusicParams()
    {
        //TODO: add whatever bullshit the power modules will do to the sound
        // i gotta be honest, idk what "more aggressive means" in this context
        return new Dictionary<string, float>();
    }

    public IReactorModule.ReactorStats MyReactorStats()
    {
        return new IReactorModule.ReactorStats()
        {
            PowerGenerated = power
        };
    }
}
